package report_generator

import (
	"fmt"
	"strconv"
	"strings"
	"time"

	_ "embed"

	"github.com/johnfercher/maroto/v2"
	"github.com/johnfercher/maroto/v2/pkg/components/col"
	"github.com/johnfercher/maroto/v2/pkg/components/row"
	"github.com/johnfercher/maroto/v2/pkg/components/text"
	"github.com/johnfercher/maroto/v2/pkg/config"
	"github.com/johnfercher/maroto/v2/pkg/consts/align"
	"github.com/johnfercher/maroto/v2/pkg/consts/fontstyle"
	"github.com/johnfercher/maroto/v2/pkg/consts/orientation"
	"github.com/johnfercher/maroto/v2/pkg/core"
	"github.com/johnfercher/maroto/v2/pkg/core/entity"
	"github.com/johnfercher/maroto/v2/pkg/props"
	"github.com/kurochkinivan/device_reporter/internal/domain"
)

//go:embed fonts/DejaVuSans.ttf
var dejavuNormal []byte

//go:embed fonts/DejaVu_Serif_Condensed_Bold.ttf
var dejavuBold []byte

type ReportGenerator struct{}

func New() *ReportGenerator {
	return &ReportGenerator{}
}

func (r *ReportGenerator) GenerateReport(outputPath, unitGUID, sourceFile string, devices []*domain.Device) error {
	cfg := config.NewBuilder().
		WithOrientation(orientation.Horizontal).
		WithPageNumber().
		WithLeftMargin(10).
		WithRightMargin(10).
		WithTopMargin(10).
		WithCompression(true).
		WithCustomFonts([]*entity.CustomFont{
			{
				Family: "DejaVuSans",
				Style:  fontstyle.Normal,
				Bytes:  dejavuNormal,
			},
			{
				Family: "DejaVuSans",
				Style:  fontstyle.Bold,
				Bytes:  dejavuBold,
			},
		}).
		Build()

	m := maroto.New(cfg)

	m.AddRows(
		row.New(12).Add(
			col.New(12).Add(
				text.New("Device Report", props.Text{
					Family: "DejaVuSans",
					Size:   16,
					Style:  fontstyle.Bold,
					Align:  align.Center,
					Color:  r.darkColor(),
				}),
			),
		),
		row.New(6).Add(
			col.New(12).Add(
				text.New(
					fmt.Sprintf("Generated: %s", time.Now().Format("2006-01-02 15:04:05")),
					props.Text{Family: "DejaVuSans", Size: 9, Align: align.Center, Color: r.grayColor()},
				),
			),
		),
		row.New(4),
	)

	// meta-info
	m.AddRows(r.buildMetaSection(unitGUID, devices[0].InvID, sourceFile, len(devices))...)

	// spacer
	m.AddRow(6)

	// table header
	m.AddRows(
		row.New(7).Add(
			col.New(12).Add(
				text.New("Event Records", props.Text{
					Family: "DejaVuSans",
					Size:   12,
					Style:  fontstyle.Bold,
					Color:  r.darkColor(),
				}),
			),
		),
	)

	// data cards
	for _, device := range devices {
		m.AddRows(r.buildDeviceCard(device)...)
	}

	// footer
	m.AddRow(6)
	m.AddRows(
		row.New(5).Add(
			col.New(12).Add(
				text.New(
					"This report was automatically generated by device-reporter service.",
					props.Text{Family: "DejaVuSans", Size: 8, Align: align.Center, Color: r.grayColor()},
				),
			),
		),
	)

	doc, err := m.Generate()
	if err != nil {
		return fmt.Errorf("failed to generate pdf: %w", err)
	}

	return doc.Save(outputPath)
}

func (r *ReportGenerator) buildMetaSection(unitGUID, invID, sourceFile string, total int) []core.Row {
	labelProps := props.Text{Family: "DejaVuSans", Size: 9, Style: fontstyle.Bold, Color: r.darkColor()}
	valueProps := props.Text{Family: "DejaVuSans", Size: 9, Color: r.darkColor()}

	makeRow := func(label, value string) core.Row {
		return row.New(7).Add(
			col.New(3).Add(text.New(label, labelProps)),
			col.New(9).Add(text.New(value, valueProps)),
		)
	}

	return []core.Row{
		makeRow("Unit GUID:", unitGUID),
		makeRow("Inventory ID", invID),
		makeRow("Source File:", sourceFile),
		makeRow("Total Records:", strconv.Itoa(total)),
		makeRow("Processed At:", time.Now().UTC().Format("2006-01-02 15:04:05 UTC")),
	}
}

func (r *ReportGenerator) buildDeviceCard(d *domain.Device) []core.Row {
	bg := r.classColor(d.Class)
	accent := r.classAccentColor(d.Class)

	rows := []core.Row{
		row.New(10).Add(
			col.New(1).WithStyle(&props.Cell{BackgroundColor: bg}).Add(
				text.New(strconv.Itoa(d.N), props.Text{Family: "DejaVuSans", Size: 11, Style: fontstyle.Bold, Color: r.darkColor()}),
			),
			col.New(9).WithStyle(&props.Cell{BackgroundColor: bg}).Add(
				text.New(d.MsgID, props.Text{Family: "DejaVuSans", Size: 10, Style: fontstyle.Bold, Color: r.darkColor()}),
			),
			col.New(2).WithStyle(&props.Cell{BackgroundColor: accent}).Add(
				text.New(strings.ToUpper(d.Class), props.Text{
					Family: "DejaVuSans", Size: 8, Style: fontstyle.Bold, Align: align.Center,
					Color: &props.Color{Red: 255, Green: 255, Blue: 255},
				}),
			),
		),

		r.buildFieldRow("TEXT / CONTEXT", fmt.Sprintf("%s / %s", d.Text, d.Context), bg),
		r.buildFieldRow("AREA / ADDR", fmt.Sprintf("%s / %s", d.Area, d.Addr), bg),
		r.buildFieldRow("LEVEL / BLOCK", fmt.Sprintf("%d / %s", d.Level, d.Block), bg),
		r.buildFieldRow("TYPE / BIT / INV", fmt.Sprintf("%s / %s / %s", d.Type, d.Bit, d.InvertBit), bg),

		row.New(4),
	}

	return rows
}

func (r *ReportGenerator) buildFieldRow(label, value string, bg *props.Color) core.Row {
	return row.New(7).Add(
		col.New(3).WithStyle(&props.Cell{BackgroundColor: bg}).Add(
			text.New(label, props.Text{Family: "DejaVuSans", Size: 7, Style: fontstyle.Bold, Color: r.grayColor()}),
		),
		col.New(9).WithStyle(&props.Cell{BackgroundColor: bg}).Add(
			text.New(value, props.Text{Family: "DejaVuSans", Size: 8, Color: r.darkColor()}),
		),
	)
}

func (r *ReportGenerator) classAccentColor(class string) *props.Color {
	switch class {
	case "alarm":
		return &props.Color{Red: 192, Green: 57, Blue: 43}
	case "warning":
		return &props.Color{Red: 230, Green: 126, Blue: 34}
	case "working":
		return &props.Color{Red: 39, Green: 174, Blue: 96}
	default:
		return &props.Color{Red: 41, Green: 128, Blue: 185}
	}
}

func (r *ReportGenerator) classColor(class string) *props.Color {
	switch class {
	case "alarm":
		return &props.Color{Red: 248, Green: 215, Blue: 218}
	case "warning":
		return &props.Color{Red: 255, Green: 238, Blue: 186}
	case "working":
		return &props.Color{Red: 212, Green: 237, Blue: 218}
	case "waiting":
		return &props.Color{Red: 222, Green: 235, Blue: 247}
	default:
		return &props.Color{Red: 255, Green: 255, Blue: 255}
	}
}

func (r *ReportGenerator) darkColor() *props.Color {
	return &props.Color{Red: 26, Green: 26, Blue: 46}
}

func (r *ReportGenerator) grayColor() *props.Color {
	return &props.Color{Red: 119, Green: 119, Blue: 119}
}
